### ISSUE TITLE
Transformer error on nested includes

### ISSUE THREAD

**Issue by jlorente** [apiato/apiato#324]
## Expected Behavior
Setting a nested value in the include param (i.e. include=location.region) the expected result is that the region object is included throught the location object. 

## Actual Behavior
An exception in thrown "Requested a invalid Include Parameter.".

## Steps to Reproduce the Problem
I will use the above example location.region
1. The current transformer must have an available include with the name "location" that will include a LocationTransformer of a Location object.
2. The LocationTransformer must have an available include with the name "region" that will include a RegionTransformer of a Region object.

## Specifications
  - Apiato Version: 7.2

## Additional Details
The problem I see here is that the transform method of the Apiato\Core\Traits\ResponseTrait is setting the requested includes as default includes on the current transformer object.
```php
    public function transform($data, $transformerName = null, array $includes = [], array $meta = [], $resourceKey = null)
    {
        $transformer = new $transformerName;

        // append the includes from the transform() to the defaultIncludes
        $includes = array_unique(array_merge($transformer->getDefaultIncludes(), $includes));

        // check if the user wants to include additional relationships
        if ($requestIncludes = Request::get('include'))
        {
            $queryIncludes = explode(',', $requestIncludes);
            $includes = array_unique(array_merge($includes, $queryIncludes));
        }

        // set the relationships to be included
        $transformer->setDefaultIncludes($includes);
       .......
```
I have found a solution by adding the requested includes to the Fractal object directly instead of merging them with the default includes of the Transformer and setting them as default.

```php
  public function transform($data, $transformerName = null, array $includes = null, array $meta = [], $resourceKey = null) {
        $transformer = new $transformerName;

        // add specific meta information to the response message
        $this->metaData = [
            'include' => $transformer->getAvailableIncludes(),
            'custom' => $meta,
        ];

        // no resource key was set
        if (!$resourceKey) {
            // get the resource key from the model
            $obj = null;
            if ($data instanceof AbstractPaginator) {
                $obj = $data->getCollection()->first();
            } elseif ($data instanceof Collection) {
                $obj = $data->first();
            } else {
                $obj = $data;
            }

            // if we have an object, try to get its resourceKey
            if ($obj) {
                $resourceKey = $obj->getResourceKey();
            }
        }

        $fractal = Fractal::create($data, $transformer)->withResourceName($resourceKey)->addMeta($this->metaData);
        if ($requestIncludes = Request::get('include')) {
            $fractal->parseIncludes($requestIncludes);
        }
        // apply request filters if available in the request
        if ($requestFilters = Request::get('filter')) {
            $result = $this->filterResponse($fractal->toArray(), explode(';', $requestFilters));
        } else {
            $result = $fractal->toArray();
        }

        return $result;
    }
}
```

**Comment by johannesschobel** [comment]
hey @jlorente ..
Can you try to to set the configuration flag for `apiato.requests.force-valid-includes` to `false` (default `true`) and try again? ;) I think that should do the trick for you!?

**Comment by johannesschobel** [comment]
hmmmmmmmmmmmmmm.. actually.. i kinda like the approach.. need to play around a little bit.. but seems to be cool!

**Comment by johannesschobel** [comment]
ok.. i just had a few minutes and took a closer look at it @jlorente .. thereby, i came up with this solution, which is a mix of BEFORE and AFTER (note the **Comments** to indicate what i had changed):

```php
public function transform($data, $transformerName = null, array $includes = [], array $meta = [], $resourceKey = null)
    {
        $transformer = new $transformerName;
        $includes = array_unique(array_merge($transformer->getDefaultIncludes(), $includes));

        // THIS PART NEEDS TO BE REMOVED
        // check if the user wants to include additional relationships
        /*
        if ($requestIncludes = Request::get('include')) {
            $queryIncludes = explode(',', $requestIncludes);
            $includes = array_unique(array_merge($includes, $queryIncludes));
        }
        */

        // set the relationships to be included
        $transformer->setDefaultIncludes($includes);

        // add specific meta information to the response message
        $this->metaData = [
            'include' => $transformer->getAvailableIncludes(),
            'custom' => $meta,
        ];

        // no resource key was set
        if (!$resourceKey) {
            // get the resource key from the model
            $obj = null;
            if ($data instanceof AbstractPaginator) {
                $obj = $data->getCollection()->first();
            }
            elseif ($data instanceof Collection) {
                $obj = $data->first();
            }
            else {
                $obj = $data;
            }

            // if we have an object, try to get its resourceKey
            if ($obj) {
                $resourceKey = $obj->getResourceKey();
            }
        }

        $fractal = Fractal::create($data, $transformer)->withResourceName($resourceKey)->addMeta($this->metaData);
        // THIS PART NEEDS TO BE ADDED
        if ($requestIncludes = Request::get('include')) {
            $fractal->parseIncludes($requestIncludes);
        }

        // apply request filters if available in the request
        if ($requestFilters = Request::get('filter')) {
            $result = $this->filterResponse($fractal->toArray(), explode(';', $requestFilters));
        }
        else {
            $result = $fractal->toArray();
        }
        return $result;
    }
```

Problem with your solution would be, that all `defaultIncludes` would be ignored.. This would cause existing APIs to break (because the expected result would differ now!).

Can you please double-check this? If you thumb-up i will make a PR and merge!

**Comment by jlorente** [comment]
Mmm, I see. In my approach I forgot to merge the includes passed as parameter. Yours is more complete. I'm going to test it.

**Comment by johannesschobel** [comment]
hey @jlorente .. kindle see the linked PR.. can you try this and give me feedback directly in the PR? That would be kind!

**Comment by jlorente** [comment]
Of course @johannesschobel

**Comment by johannesschobel** [comment]
closed this for now, as i have merged the PR

**Comment by rmdwirizki** [comment]
Still having this problem in Apiato version 7.4.

In case someone meet the same problem. My fix is to remove this line:
```php
// set the relationships to be included
$transformer->setDefaultIncludes($includes);
```
And change it to `parseIncludes` method:
```php
// Insert parse here include
// set the relationships to be included
$fractal->parseIncludes($includes);
```

Override the `transform` function in `App\Ship\Parents\Controllers\ApiController`
```php
<?php

namespace App\Ship\Parents\Controllers;

use Request;
use Spatie\Fractalistic\Fractal;
use Apiato\Core\Abstracts\Controllers\ApiController as AbstractApiController;

/**
 * Class ApiController.
 *
 * @author  Mahmoud Zalt <mahmoud@zalt.me>
 */
abstract class ApiController extends AbstractApiController
{
  /* Override Apiato\Core\Traits\ResponseTrait transform function */
  /**
   * @param       $data
   * @param null  $transformerName
   * @param array $includes
   * @param array $meta
   * @param null  $resourceKey
   *
   * @return array
   */
  public function transform(
    $data,
    $transformerName = null,
    array $includes = [],
    array $meta = [],
    $resourceKey = null
  ) {
    // create instance of the transformer
    $transformer = new $transformerName;

    // append the includes from the transform() to the defaultIncludes
    $includes = array_unique(array_merge($transformer->getDefaultIncludes(), $includes));

    /* REMOVE THIS */
    // set the relationships to be included
    // $transformer->setDefaultIncludes($includes);
    /* REMOVE THIS */

    // add specific meta information to the response message
    $this->metaData = [
      'include' => $transformer->getAvailableIncludes(),
      'custom'  => $meta,
    ];

    // no resource key was set
    if (!$resourceKey) {
      // get the resource key from the model
      $obj = null;
      if ($data instanceof AbstractPaginator) {
        $obj = $data->getCollection()->first();
      } elseif ($data instanceof Collection) {
        $obj = $data->first();
      } else {
        $obj = $data;
      }

      // if we have an object, try to get its resourceKey
      if ($obj) {
        $resourceKey = $obj->getResourceKey();
      }
    }

    $fractal = Fractal::create($data, $transformer)->withResourceName($resourceKey)->addMeta($this->metaData);

    /* INSERT THIS */
    // set the relationships to be included
    $fractal->parseIncludes($includes);
    /* INSERT THIS */

    // check if the user wants to include additional relationships
    if ($requestIncludes = Request::get('include')) {
      $fractal->parseIncludes($requestIncludes);
    }

    // apply request filters if available in the request
    if ($requestFilters = Request::get('filter')) {
      $result = $this->filterResponse($fractal->toArray(), explode(';', $requestFilters));
    } else {
      $result = $fractal->toArray();
    }

    return $result;
  }
}
```
