### ISSUE TITLE
Hashids doesn't get the values from the right config

### ISSUE THREAD

**Issue by Mohammad-Alavi** [apiato/apiato#550]
### Description:
Hashids doesn't get the values from the config in
Ship\Configs\hashids.php
and instead use its default values. 

### Expected Behavior:
When i set
HASH_ID_LENGTH=16
in .env the length of the encoded value should be 16 but it will return 2 which is the default length.

### Additional Context:
This was working fine before Apiato 9.0 upgrade.

### Versions:
- Apiato Version: 9.0.0
- PHP Version: 7.4.3

### Steps To Reproduce:
1. $model->getHashedKey()
or
2. Hashids::encode(1)

**Comment by Mohammad-Alavi** [comment]
It is fixed by itself 🤨

**Comment by ikeedo** [comment]
@Mohammad-Alavi I am still having this problem like you described, even after doing a fresh install of everything. What did you to get rid of the problem?

**Comment by Mohammad-Alavi** [comment]
I really cant remember doing anything special but ill tell you what i can remember.

I was using homestead, vagrant. with box version 9.3.0

I tried vagrant destroy, up, reload, --provision with no luck and i went to do other things with hope to find a way to fix it later so i stopped checking if it is fixed or not. And last night i updated my vagrant box to 9.4.0 and when i was working today i suddenly realized that this problem is fixed 🤔

Try to update your vagrant box to the latest version if you are using vagrant.

**Comment by ikeedo** [comment]
@Mohammad-Alavi Thanks for your reply. I am working with Laradock, so maybe I should completely delete the images with cache or just try on a new machine. Good to know it git fixed by itself for you, so I can hope for this magic solution for myself :-D

**Comment by ikeedo** [comment]
Update – perhaps it helps others who run into this issue:

I have copied the config from `/app/Ship/Configs/hashids.php` to `/config/hashids.php`, that worked for me! Apparently Laravel isn't getting the Apiato config after the update. That might be some caching/versioning error with my environment, but may not be unusual, since you ran into the same problem.

**Comment by darkons** [comment]
I had same issue recently and seems to be an Apiato mistake with composer install command.

Copy of hashids.php to /config is not neccesary. Just make the following steps:

- Delete vendor folder
- Delete composer.lock
- Run `composer install` (this will not install packages from Ship/core/composer.json)
- Run `composer update` (now packages from Ship/core/composer.json will be installed)

Don't know why running `composer install`, packages from Ship/core/composer.json are not installed.
